package ictgradschool.industry.swing.examples.example4;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * An example showing how we can differentiate between ActionEvents generated by different components.
 */
public class ExampleFour extends JPanel implements ActionListener {

    private JTextField textField;
    private JButton leftButton, rightButton;

    /**
     * Creates a new ExampleThree panel, which has a button and a text field.
     */
    public ExampleFour() {

        this.leftButton = new JButton("Left!");
        this.add(leftButton);
        this.leftButton.addActionListener(this);

        this.textField = new JTextField(30);
        this.add(textField);

        this.rightButton = new JButton("Right!");
        this.add(rightButton);
        this.rightButton.addActionListener(this);

    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == leftButton) {
            textField.setText("Left!");
        }
        else if (e.getSource() == rightButton) {
            textField.setText("Right!");
        }
    }

    /**
     * Program entry point. Creates a new JFrame and adds an instance of this ExampleThree panel as its content.
     * @param args
     */
    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                JFrame myFrame = new JFrame();
                myFrame.setLocation(100, 100);
                myFrame.setTitle("Example Four: Handling ActionEvents from multiple sources");
                myFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

                ExampleFour ex3 = new ExampleFour();
                myFrame.getContentPane().add(ex3);
                myFrame.pack();
                myFrame.setVisible(true);

            }
        });
    }
}
