package ictgradschool.industry.swing.examples.example3;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * A simple panel which demonstrates how we can handle ActionEvents generated by button clicks.
 */
public class ExampleThree extends JPanel implements ActionListener {

    private JTextField textField;

    /**
     * Creates a new ExampleThree panel, which has a button and a text field.
     */
    public ExampleThree() {

        JButton button = new JButton("Click me!");
        this.add(button);
        button.addActionListener(this);

        this.textField = new JTextField(30);
        this.add(textField);

    }

    @Override
    public void actionPerformed(ActionEvent e) {
        textField.setText("The button was clicked!");
    }

    /**
     * Program entry point. Creates a new JFrame and adds an instance of this ExampleThree panel as its content.
     * @param args
     */
    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                JFrame myFrame = new JFrame();
                myFrame.setLocation(100, 100);
                myFrame.setTitle("Example Three: A ActionListener");
                myFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

                ExampleThree ex3 = new ExampleThree();
                myFrame.getContentPane().add(ex3);
                myFrame.pack();
                myFrame.setVisible(true);

            }
        });
    }
}
