package ictgradschool.industry.swing.examples.example5;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * A simple panel which demonstrates how we can handle ActionEvents generated by button clicks.
 */
public class ExampleFive extends JPanel implements ActionListener {

    private int ovalX, ovalY, ovalWidth, ovalHeight;

    /**
     * Creates a new ExampleFive panel, which has a button.
     */
    public ExampleFive() {

        setPreferredSize(new Dimension(500, 500));

        JButton button = new JButton("Click me!");
        this.add(button);
        button.addActionListener(this);

        randomOval();
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        randomOval();
    }

    /**
     * Randomizes the size of the oval that's drawn on this Panel, then calls repaint() to tell Swing it should redraw
     * this panel.
     */
    private void randomOval() {

        ovalWidth = (int)(Math.random() * 200) + 100;
        ovalHeight = (int)(Math.random() * 200) + 100;
        ovalX = (int) (Math.random() * (getWidth() - ovalWidth));
        ovalY = (int) (Math.random() * (getHeight() - ovalHeight));

        repaint();
    }

    /**
     * In addition to any child components (e.g. the JButton), this panel also draws an oval of a certain size when
     * it renders itself.
     *
     * @param g the {@link Graphics} object to use to draw the oval
     */
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        g.drawOval(ovalX, ovalY, ovalWidth, ovalHeight);
    }

    /**
     * Program entry point. Creates a new JFrame and adds an instance of this ExampleThree panel as its content.
     * @param args
     */
    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                JFrame myFrame = new JFrame();
                myFrame.setTitle("Example Five: Use of repaint()");
                myFrame.setLocation(100, 100);
                myFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

                ExampleFive ex3 = new ExampleFive();
                myFrame.getContentPane().add(ex3);
                myFrame.pack();
                myFrame.setVisible(true);

            }
        });
    }
}
